{{- if and .Values.grafana.enabled .Values.grafana.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubepolaris.fullname" . }}-grafana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubepolaris.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  accessModes:
    - {{ .Values.grafana.persistence.accessMode }}
  {{- if .Values.grafana.persistence.storageClass }}
  {{- if (eq "-" .Values.grafana.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.grafana.persistence.storageClass }}
  {{- end }}
  {{- else if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
{{- end }}
