{{- if and .Values.mysql.internal.enabled .Values.mysql.internal.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubepolaris.fullname" . }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubepolaris.mysql.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mysql.internal.persistence.accessMode }}
  {{- if .Values.mysql.internal.persistence.storageClass }}
  {{- if (eq "-" .Values.mysql.internal.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.mysql.internal.persistence.storageClass }}
  {{- end }}
  {{- else if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mysql.internal.persistence.size }}
{{- end }}
